# SMTP config for forgot-password email (used by PasswordRecoveryEmailService)
# Priority order at runtime: -D properties > environment variables > this file > defaults

auticare.smtp.user=amarahedil8@gmail.com
auticare.smtp.appPassword=ihdv qimv lptx sodk
auticare.smtp.host=smtp.gmail.com
auticare.smtp.port=587

oauth.google.clientId=587132376056-f81kk0s6greoqmd2hitpamq9jtjsnngr.apps.googleusercontent.com
oauth.google.clientSecret=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
oauth.google.redirectUri=http://127.0.0.1:8888/oauth/callback/
 